---
name: Ejercitación - Layout
locale: es
type: learning
beta: false
teacher_info: ''
language: html
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 7
- 8
- 7
- 7
- 11
- 10
- 8
- 11
- 7
- 10
- 9
private: false
