---
name: Ejercitación - Layout
locale: es
type: learning
beta: false
teacher_info: ''
language: html
id_format: "%05d"
order:
- 1
- 1
- 1
- 2
- 2
- 2
- 3
- 3
- 4
- 4
- 4
- 2
- 1
- 5
- 5
- 5
- 6
- 6
- 6
- 7
- 7
- 7
- 4
- 8
- 8
- 9
- 5
- 11
- 3
- 11
- 6
- 2
- 3
- 7
- 1
- 4
- 8
- 5
- 10
- 11
- 10
- 6
- 3
- 7
- 9
- 10
- 9
- 12
private: false
