---
name: Ejercitación - Introducción a CSS
locale: es
type: learning
beta: false
teacher_info: ''
language: html
id_format: "%05d"
order:
- 1
- 1
- 2
- 2
- 3
- 3
- 4
- 4
- 5
- 5
- 6
- 6
- 7
- 7
- 8
- 9
- 10
- 11
private: false
